// Generated by Prism
//
// HOW TO USE:
// 1. Copy this file to .storybook/prism-preview.ts
// 2. In .storybook/preview.ts add at the top:
//      import './prism-preview'
// 3. Install the themes addon (once):
//      npm install --save-dev @storybook/addon-themes
// 4. Add '@storybook/addon-themes' to addons in .storybook/main.ts

import '../tokens/tokens.css'

import { withThemeByDataAttribute } from '@storybook/addon-themes'

export const decorators = [
  withThemeByDataAttribute({
    themes: {
      Default: '',
      'Andal Kharisma': 'andal-kharisma',
      'Andal SAIS': 'andal-sais',
      'Andal Performance': 'andal-performance',
      'Andal Talent': 'andal-talent'
    },
    defaultTheme: 'Default',
    attributeName: 'data-theme',
  }),
]
